<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInite97323223dcbe4b9a8b1df6c6215b219
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'Psr\\SimpleCache\\' => 16,
            'Psr\\Container\\' => 14,
        ),
        'K' => 
        array (
            'Krishnahimself\\DateConverter\\Database\\Factories\\' => 48,
            'Krishnahimself\\DateConverter\\' => 29,
        ),
        'I' => 
        array (
            'Illuminate\\Contracts\\' => 21,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Psr\\SimpleCache\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/simple-cache/src',
        ),
        'Psr\\Container\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/container/src',
        ),
        'Krishnahimself\\DateConverter\\Database\\Factories\\' => 
        array (
            0 => __DIR__ . '/..' . '/krishnahimself/laravel-ad-to-bs-converter/database/factories',
        ),
        'Krishnahimself\\DateConverter\\' => 
        array (
            0 => __DIR__ . '/..' . '/krishnahimself/laravel-ad-to-bs-converter/src',
        ),
        'Illuminate\\Contracts\\' => 
        array (
            0 => __DIR__ . '/..' . '/illuminate/contracts',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInite97323223dcbe4b9a8b1df6c6215b219::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInite97323223dcbe4b9a8b1df6c6215b219::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInite97323223dcbe4b9a8b1df6c6215b219::$classMap;

        }, null, ClassLoader::class);
    }
}
